version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: akthakorn/vue-job-project-frontend:latest
    ports:
      - "8080:80"
    # depends_on:
    #   api:
    #     condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  api:
    build:
      context: ./data
      dockerfile: Dockerfile
    image: akthakorn/vue-job-project-api:latest
    command: -h 0.0.0.0 -p 8001 -s ./public jobs.json
    ports:
      - "8001:8000"
    init: true
    volumes:
      - ./data:/data
    restart: unless-stopped
    networks:
      - app-network
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000"]  # Checks if API is responding
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3

networks:
  app-network:
    driver: bridge
