name: CD Pipeline

on:
  push:
    workflow_run:
      workflows: ["CI Pipeline"]
      types:
        - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Check out code
    - uses: actions/checkout@v4

    - name: Remove all Containers
      run: |
        sudo docker container prune -f

    - name: Run docker-compose
      run: |
        sudo docker-compose up -d
