name: CD Pipeline

on:
  push:
    workflow_run:
      workflows: ["CI Pipeline"]
      types: 
        - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Latest Docker Images
      run: |
        sudo docker-compose -f docker-compose.yml pull

    - name: Stop and Remove Old Containers
      run: |
        sudo docker-compose -f docker-compose.yml down || true

    - name: Run Docker Containers
      run: |
        sudo docker-compose -f docker-compose.yml up -d
