name: CD Pipeline

on:
  push:
    workflow_run:
      workflows: ["CI Pipeline"]
      types:
        - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Pull Latest Docker Images
      run: sudo docker-compose -f docker-compose.yml pull

    - name: Stop and Remove Old Containers
      run: |
        sudo docker-compose -f docker-compose.yml down || true

    - name: Run Docker Containers
      run: |
        sudo docker-compose -f docker-compose.yml up -d
