name: CD Pipeline

on:
  push:
    workflow_run:
      workflows: ["CI Pipeline"]
      types: 
        - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker Image
      run: sudo docker pull ${{secrets.DOCKER_USER}}/vue-job-project-frontend:latest
    - name: Delete Old Docker Container
      run: sudo docker rm -f vue-job-project-frontend || true
    - name: Run Docker Container
      run: sudo docker run -d -p 80:80 --name vue-job-project-frontend ${{secrets.DOCKER_USER}}/vue-job-project-frontend
