name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login Docker Hub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
      # Install Docker Compose if not already installed
    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose  

      # Build images as per docker-compose.yml
    - name: Build Docker Compose services
      run: docker-compose -f docker-compose.yml build  

      # Push frontend image to Docker Hub
      # Push API image to Docker Hub
    - name: Push Docker images
      run: |
        docker-compose -f docker-compose.yml push frontend  
        docker-compose -f docker-compose.yml push api  
